name: Pipeline

on:
  push:
    branches:
      - feature/devsecops-pipeline

jobs:
  devsecops:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Clonación del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Dar permisos a Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar proyecto con Gradle
        run: ./gradlew clean build -x test

      - name: Ejecutar análisis SAST con CodeQL
        uses: github/codeql-action/analyze@v4
      
      - name: Validar vulnerabilidades SAST Medium High Critical
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Esperando publicación de resultados CodeQL..."
          sleep 30

          ALERTS=$(gh api \
            "/repos/${{ github.repository }}/code-scanning/alerts?state=open&branch=${{ github.ref_name }}" \
            --jq '.[] | select(
              .rule.security_severity_level=="medium" or
              .rule.security_severity_level=="high" or
              .rule.security_severity_level=="critical" or
              .rule.severity=="medium" or
              .rule.severity=="high" or
              .rule.severity=="critical"
            ) | .rule.description')

          if [ -n "$ALERTS" ]; then
            echo "Se detectaron vulnerabilidades SAST Medium/High/Critical:"
            echo "$ALERTS"
            exit 1
          else
            echo "No se detectaron vulnerabilidades SAST Medium/High/Critical."
          fi

        
