name: Pipeline DevSecOps - Docker Build

on:
  push:
    branches:
      - feature/devsecops-pipeline

jobs:
  DOCKER_BUILD:
    runs-on: ubuntu-latest

    steps:
      - name: Clonación del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Dar permisos a Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar proyecto con Gradle
        run: ./gradlew clean build -x test

      - name: Construir imagen Docker
        run: docker build -t pet-clinic:${{ github.sha }} .

      - name: Listar imagen Docker generada
        run: docker images | grep pet-clinic
