  SCA:
    runs-on: ubuntu-latest

    steps:
      - name: Clonación del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Cache OWASP Dependency Check
        uses: actions/cache@v4
        with:
          path: |
            dependency-check
            ~/.dependency-check
          key: dependency-check-cache-${{ runner.os }}
          restore-keys: |
            dependency-check-cache-${{ runner.os }}-

      - name: Dar permisos a Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar proyecto con Gradle
        run: ./gradlew clean build -x test

      - name: Instalar OWASP Dependency Check
        run: |
          if [ ! -f dependency-check/bin/dependency-check.sh ]; then
            curl -L -o dependency-check.zip https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
            unzip dependency-check.zip
          else
            echo "OWASP Dependency Check encontrado en cache"
          fi

      - name: Ejecutar SCA con OWASP Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "pet-clinic" \
            --scan "." \
            --format "HTML" \
            --out "reports" \
            --enableRetired \
            --disableOssIndex \
            --failOnCVSS 5

      - name: Publicar reporte SCA
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
